# Generated by Django 3.1 on 2020-08-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='static/images/gallery/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='static/video/'),
        ),
    ]
